### ISSUE TITLE
crs as line endings in at least app/App.js

### ISSUE THREAD

**Issue by tnt** [pro-react/react-app-boilerplate#4]
I think lfs were neutral.

**Comment by cassiozen** [comment]
Hi,

Could you please elaborate on this? Can you do a pull request?

**Comment by tnt** [comment]
The following diff shows _graphically_ the difference bewteen **is** and **should**:

``` diff
diff --git a/app/App.js b/app/App.js
index f18de61..cc308d1 100755
--- a/app/App.js
+++ b/app/App.js
@@ -1 +1,12 @@
-import React, { Component } from 'react';^Mimport {render} from 'react-dom';^Mclass App extends Component {^M  render(){^M    return (^M      <h1>Hello World</h1>^M    );^M  }^M}^Mrender(<App />, document.getElementById('root'));
\ No newline at end of file
+import React, { Component } from 'react';
+import {render} from 'react-dom';
+
+class App extends Component {
+  render(){
+    return (
+      <h1>Hello World</h1>
+    );
+  }
+}
+
+render(<App />, document.getElementById('root'));
```

In `git` on Windows there are settings to make git convert line endings when checking in/out. Maybe there is something equal for git on MacOs. But I suppose that all editors/IDEs also can work with unix line-endings without any problems. You'd just have to change some settings.

**Comment by jaredhirsch** [comment]
Hey @cassiozen,

I just ran into this issue as well on current Mac OS (10.11). The line-endings in this file aren't compatible with linux/mac.

[Here's](http://blog.codinghorror.com/the-great-newline-schism/) a nice article on the history of how and why newline character sequences differ across different operating systems.

If you use vim as your editor, it's really easy to convert the line endings in a given file, and to update your editor so this doesn't happen again. [This page](http://vim.wikia.com/wiki/File_format) explains how to detect which type of ending your editor is configured to use, as well as instructions on converting files.

As is discussed on the vim page linked above, the current bug is due to loading a file that uses old Mac style line endings with an editor that expects Unix line endings.

What OS and what editor do you generally use? I'm happy to help you find resources to sort this out, as this problem will make it hard to submit patches to most open source projects.

Just so you're aware, this isn't only an issue with line endings in editors; it's also an issue in tools, like git, that expect unix line endings. For example, here's the output of `git log -p App.js` on my Mac:

![](https://www.dropbox.com/s/69uynilqsulygtx/Screen%20Shot%202016-04-07%20at%207.04.26%20PM.png?dl=0&raw=true)

**Comment by cassiozen** [comment]
Hi @6a68, @tnt 
It's weird because all these files were authored on a Mac - but I agree with you guys: this is not ideal.
